name: Build FlyskyIBUS Example Sketch

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  checking_lib:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32:esp32:esp32
          sketch-paths: examples/read_Channels/read_Channels.ino
